const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./router.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Endpoints",
      description: "User and Product endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
  },
  definitions: {
    UserCredentials: {
      email: "email@email.com",
      password: "123@4",
    },
    AddUser: {
      name: "Fulano de Tal",
      profession: "Administrador",
      birthDate: "1980-09-29",
      documentNumber: "01234567890",
      phone: "11985476932",
      email: "email@email.com",
      password: "123@4",
      address: {
        zipCode: "42800049",
        street: "Rua Costa Pinto",
        number: 254,
        complement: null,
        neighborhood: "Centro",
        city: "Camaçari",
        state: "BA",
      },
    },
    Product: {
      id: "3961048c-9242-45a2-92b3-11d24023cd5b",
      name: "Smartphone Sony",
      descriptiom: "Descricao do produto",
      price: 1000,
      quantity: 10,
      image:
        "https://www.google.com/imgres?q=iphone%2015&imgurl=https%3A%2F%2Fstore.storeimages.cdn-apple.com%2F1%2Fas-images.apple.com%2Fis%2Fiphone-15-pro-finish-select-202309-6-7inch-blacktitanium_AV1%3Fwid%3D5120%26hei%3D2880%26fmt%3Dp-jpg%26qlt%3D80%26.v%3DVW44dkRidm5wazhwcGxtL0cyaEJ2VTkrNXBUdUJSK1k4NE5seUtJaW80ZEVRNFN1aThHM1R3Z1g3RUVXYlJtU0NUcEx1KzZ4TU5aSmJ4VzBKZWFPSGppOHgxUjM1bG1hRnArQXQ1elR1Rk13Qjhvd1BnZkhnUFFYU1JJMGh5alE5MDdNZE9taTJHQm5YeTNRMlpyNWxYNXFNVzc5YkZmK2I4YzJ4ZndkZUdjPQ%3D%3D%26traceId%3D1&imgrefurl=https%3A%2F%2Fwww.apple.com%2Fbr%2Fshop%2Fbuy-iphone%2Fiphone-15-pro%2Ftela-de-6%2C7-polegadas-512gb-tit%25C3%25A2nio-preto&docid=Zug88VXe4nXssM&tbnid=wulXIGBik6FnCM&vet=12ahUKEwil44zg5fKFAxVLppUCHVV8AmQQM3oECD4QAA..i&w=5120&h=2880&hcb=2&ved=2ahUKEwil44zg5fKFAxVLppUCHVV8AmQQM3oECD4QAA",
      tags: ["tech", "phones"],
    },
    AddProduct: {
      name: "Smartphone Sony",
      descriptiom: "Descricao do produto",
      price: 1000,
      quantity: 10,
      image:
        "https://www.google.com/imgres?q=iphone%2015&imgurl=https%3A%2F%2Fstore.storeimages.cdn-apple.com%2F1%2Fas-images.apple.com%2Fis%2Fiphone-15-pro-finish-select-202309-6-7inch-blacktitanium_AV1%3Fwid%3D5120%26hei%3D2880%26fmt%3Dp-jpg%26qlt%3D80%26.v%3DVW44dkRidm5wazhwcGxtL0cyaEJ2VTkrNXBUdUJSK1k4NE5seUtJaW80ZEVRNFN1aThHM1R3Z1g3RUVXYlJtU0NUcEx1KzZ4TU5aSmJ4VzBKZWFPSGppOHgxUjM1bG1hRnArQXQ1elR1Rk13Qjhvd1BnZkhnUFFYU1JJMGh5alE5MDdNZE9taTJHQm5YeTNRMlpyNWxYNXFNVzc5YkZmK2I4YzJ4ZndkZUdjPQ%3D%3D%26traceId%3D1&imgrefurl=https%3A%2F%2Fwww.apple.com%2Fbr%2Fshop%2Fbuy-iphone%2Fiphone-15-pro%2Ftela-de-6%2C7-polegadas-512gb-tit%25C3%25A2nio-preto&docid=Zug88VXe4nXssM&tbnid=wulXIGBik6FnCM&vet=12ahUKEwil44zg5fKFAxVLppUCHVV8AmQQM3oECD4QAA..i&w=5120&h=2880&hcb=2&ved=2ahUKEwil44zg5fKFAxVLppUCHVV8AmQQM3oECD4QAA",
      tags: ["tech", "phones"],
    },
    Products: [{ $ref: "#/definitions/Product" }],
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app");
});
